name: Docker Image CI - Manual

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag à builder"
        required: true
      latest:
        description: "Ajouter le tag latest ?"
        type: boolean
        required: false
        default: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.tag }}

      - uses: mr-smithers-excellent/docker-build-push@v7
        name: Build & push Docker image
        with:
          image: vnozais/shivai
          tags: ${{ inputs.tag }}
          addLatest: ${{ inputs.latest }}
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME_VN }}
          password: ${{ secrets.DOCKER_PASSWORD_VN }}
